/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stm32f103xx.h"


int main(void)
{
	GPIO_InitTypeDef gpioInit;

	SystemClock_Config(SYSCLK_FREQ_72MHZ);		// Other SYSCLK options are available
	RCC_GPIOA_CLK_ENABLE();

	gpioInit.Pin = GPIO_PIN_3;
	gpioInit.Mode = GPIO_MODE_OUTPUT_PP;
	gpioInit.Pull = GPIO_NOPULL;
	gpioInit.Speed = GPIO_SPEED_FREQ_LOW;

	GPIO_Init(GPIOA, &gpioInit);


	while(1)
	{
		GPIO_TogglePin(GPIOA, GPIO_PIN_3);
		Delay_ms(1);
	}
}









