/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stm32f103xx.h"


int main(void)
{
	SystemClock_Config(SYSCLK_FREQ_72MHZ);		// Other SYSCLK options are available

	RCC->CFGR |= RCC_CFGR_MCOSEL_SYSCLK;		// Select SYSCLK as MCO output

	RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;			// Clock enable GPIOA

	GPIOA->CRH &= ~(0x3 << 2);					// Clear CNF field of PA8
	GPIOA->CRH |= 0x3;							// Configure PA8 as Output mode of max speed 50MHz
	GPIOA->CRH |= (0x1 << 3);					// Configure PA8 as Alternate Function output Push-pull


	while(1);
}





